name: Chrome Extension Checks

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate manifest JSON
        run: python3 -m json.tool manifest.json > /dev/null

      - name: Check Chrome manifest requirements
        run: npx --yes chrome-manifest-validator manifest.json

      - name: Check JavaScript syntax
        shell: bash
        run: |
          set -euo pipefail
          for file in service-worker.js content.js popup.js options.js background.js; do
            echo "Checking $file"
            node --check "$file"
          done

      - name: Smoke packaging
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p out
          zip -r out/instafile.zip . -x 'out/*' '.git/*'
          unzip -t out/instafile.zip
          rm -f out/instafile.zip
